#pragma once

enum TailsActions : Uint8 {
	Act_Tails_Init,
	Act_Tails_Stand,
	Act_Tails_Walk,
	Act_Tails_Path,
	Act_Tails_Roll,
	Act_Tails_DashSpeedPanel,
	Act_Tails_Jump,
	Act_Tails_Spring,
	Act_Tails_Launch,
	Act_Tails_Paralyzed,
	Act_Tails_Fall,
	Act_Tails_Brake,
	Act_Tails_Push,
	Act_Tails_Damage,
	Act_Tails_Back,
	Act_Tails_Fly,
	Act_Tails_Knocked,
	Act_Tails_Slide,
	Act_Tails_ObjectControl,
	Act_Tails_Tired,
	Act_Tails_TailAttack,
	Act_Tails_Pick,
	Act_Tails_Put,
	Act_Tails_Hold,
	Act_Tails_HoldTree,
	Act_Tails_ObjectWalk,
	Act_Tails_Throw,
	Act_Tails_ObjectBrake,
	Act_Tails_ObjectFall,
	Act_Tails_ObjectJump,
	Act_Tails_ObjectSpring,
	Act_Tails_ObjectLaunched,
	Act_Tails_Pull,
	Act_Tails_AirThrow,
	Act_Tails_ShakeTree,
	Act_Tails_Shaken,
	Act_Tails_MonkeyBars,
	Act_Tails_MonkeyBarsOn,
	Act_Tails_Ladder,
	Act_Tails_LadderOn,
	Act_Tails_JumpPanel,
	Act_Tails_JumpPanelOn,
	Act_Tails_Captured,
	Act_Tails_BumperCar,
	Act_Tails_SkyDeckCyl,
	Act_Tails_SkyDeckCylDown,
	Act_Tails_SkyDeckCylLeft,
	Act_Tails_SkyDeckCylRight,
	Act_Tails_BoardSlide,
	Act_Tails_BoardSlideF,
	Act_Tails_BoardBrake,
	Act_Tails_BoardFall,
	Act_Tails_BoardJump,
	Act_Tails_BoardTrick,
	Act_Tails_BoardHurt,
	Act_Tails_PinBall,
	Act_Tails_PinBallFall,
	Act_Tails_Shower,
	Act_Tails_Event,
	Act_Tails_Drown,
	Act_Tails_Death,
	Act_Tails_DashHoop,
	Act_Tails_LevelResult,
	Act_Tails_PetStart,
	Act_Tails_Pet,
	Act_Tails_PetSop,
	Act_Tails_Whistle,
	Act_Tails_Debug,

	// Custom:

	Act_Tails_TailsGrab,
	Act_Tails_SpinDash
};

enum TailsAnimations {
	Anm_Tails_Stand,
	Anm_Tails_Land,
	Anm_Tails_StandAfterLand,
	Anm_Tails_JumpOrSpin = 14,
	Anm_Tails_Roll = 15,
	Anm_Tails_Fall = 19,
	Anm_Tails_Uncurl = 36,
	Anm_Tails_Fly = 37,
	Anm_Tails_RockVertHang = 100
};